### ISSUE TITLE
Awesome Tool

### ISSUE THREAD

**Issue by qkniazi** [jenkinsci/sqlplus-script-runner-plugin#10]
@boaglio it is working fine for me. I am able to run sql files from bitbucket and also from local machine. One thing that I want to know. For 10 files I created 10 jobs. is there any way that I can just say "*.sql "  means it should be able to run all files with .sql extention. in sigle job.

**Comment by boaglio** [comment]
Hi, you can't do that because it is a SQL*Plus limitation. You can solve it in Oracle way, creating one script to call all the others.
