### ISSUE TITLE
Oracle DB goes down, post DB restart triggered from jenkins, by executing shellscript

### ISSUE THREAD

**Issue by RMOHANEV** [jenkinsci/sqlplus-script-runner-plugin#11]
I have a db restart shell script as below, On executing the below shell script from jenkins [shell script added in Execute shell section], the job is executed successfully, but the DB goes down post the job is complete. Please help.

dbrestart.sh:
export ORACLE_HOME=<oracle home path>
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=DBNAME
$ORACLE_HOME/bin/sqlplus '/as sysdba' << EOM
shutdown immediate;
EOM
$ORACLE_HOME/bin/sqlplus '/as sysdba' << EOM
startup;
EOM

**Comment by boaglio** [comment]
This script has nothing to do with SQL*Plus Jenkins plugin, it is a shell based problem. Why are you not using Oracle scripts dbstart/dbshut ? http://www.dba-oracle.com/t_linux_dbstart_dbshut.htm
