### ISSUE TITLE
Jenkins DSL/Pipelines

### ISSUE THREAD

**Issue by WesleyWeber** [jenkinsci/sqlplus-script-runner-plugin#13]
@boaglio,

Are there examples on how to use SQLPlus Script Runner on the new declarative pipeline or the old style groovy scripts for Jenkins? I've just spent a few days trying to figure it out and figured at this point I should ask.

Thank you in advanced - sorry this isn't a real "issue" as in defect/bug.

Thanks.

**Comment by WesleyWeber** [comment]
Just an FYI to everyone that I've yet to find the solution on my own for this.

**Comment by boaglio** [comment]
Sorry for my late answer... do you mind share your workaround ?

**Comment by WesleyWeber** [comment]
My workaround so far has been to tell the developers "you can't use this in declarative pipeline scripts yet - it has to be a manual build step configured within Jenkins". If I'm missing something obvious, please let me know :)

**Comment by ericgrysko** [comment]
Ancient issue here, but for folks who stumble upon this looking to use plugin. If you're looking to use this plugin with Job DSL -- it does work with https://github.com/jenkinsci/job-dsl-plugin/wiki/Dynamic-DSL

Thanks to @ezmac for tip

**Comment by boaglio** [comment]
Fixed on release 2.0.1

Samples:

## user defined script
 
node {
   echo 'SQLPlusRunner running user define script for system@xe'
   step([$class: 'SQLPlusRunnerBuilder',credentialsId:'system', instance:'xe',scriptType:'userDefined', script: '',scriptContent: 'select * from v$version'])
}

## file script

node {
   echo 'SQLPlusRunner running file script for system@xe'
   step([$class: 'SQLPlusRunnerBuilder',credentialsId:'system', instance:'xe',scriptType:'file', script: 'start.sql',scriptContent: ''])
}
