### ISSUE TITLE
SQLPlus Script Runner Plugin running script stuck on build

### ISSUE THREAD

**Issue by sameek** [jenkinsci/sqlplus-script-runner-plugin#16]
I have to run sql script in remote oracle database using jenkins.I have install jenkins plugin "SQLPlus Script Runner" and configured. it work well some time when script file contains less line of sql statement but on my case it's 12000+ line of script to run. it executed few table script then running forever nothing is executing on database.

Oracle Client: instantclient_12_2
Jenkins server Operation System:Windows 7
Jenkins version ;Jenkins ver. 2.89.2
Where SQLPlus Script Runner is running (local machine or slave machine);local machine
Slave machine Operation System (if applicable);
Oracle Database version;12C
Oracle SQL*Plus version;SQL*Plus: Release 12.2.0.1.0 Production
Build log with debug info enabled.
16:41:25 --------------------------------------------------------------------------
16:41:25 Getting ORACLE_HOME...
16:41:25 custom ORACLE_HOME selected
16:41:25 --------------------------------------------------------------------------
16:41:25 Using custom ORACLE_HOME
16:41:25 --------------------------------------------------------------------------
16:41:25 Using ORACLE_HOME =D:\tools\oracleClient
16:41:25 --------------------------------------------------------------------------
16:41:25 Getting SQLPlus version
16:41:25 ORACLE_HOME = D:\tools\oracleClient
16:41:25 LD_LIBRARY_PATH = D:\tools\oracleClient\lib
16:41:25 SQL*Plus exec file = sqlplus.exe
16:41:25 found SQL*Plus on D:\tools\oracleClient
16:41:25 --------------------------------------------------------------------------
16:41:25 Statement:
16:41:25 D:\tools\oracleClient\\sqlplus.exe -v  
16:41:25 --------------------------------------------------------------------------
16:41:25 Process exited with status 0
16:41:25 --------------------------------------------------------------------------
16:41:25 
16:41:25 SQL*Plus: Release 12.2.0.1.0 Production
16:41:25 
16:41:25 testing directory D:\tools\oracleClient
16:41:25 --------------------------------------------------------------------------
16:41:25 Using ORACLE_HOME =D:\tools\oracleClient
16:41:25 --------------------------------------------------------------------------
16:41:25 Running script C:\Jenkinserver\workspace\NAPF\NAPF_SERVER_SOURCE/databasescript/NAPF_DBScript.sql em ZENKIN_USER1/********@10.254.6.198:1521/NAPFDB
16:41:25 testing script C:\Jenkinserver\workspace\NAPF\NAPF_SERVER_SOURCE\databasescript\NAPF_DBScript.sql
16:41:25 --------------------------------------------------------------------------
16:41:25 ORACLE_HOME = D:\tools\oracleClient
16:41:25 LD_LIBRARY_PATH = D:\tools\oracleClient\lib;D:\tools\oracleClient
16:41:25 found TNSNAMES.ORA on D:\tools\oracleClient\network\admin
16:41:25 TNS_ADMIN = D:\tools\oracleClient\network\admin
16:41:25 Work Directory = C:\Jenkinserver\workspace\NAPF
16:41:25 SQL*Plus exec file = sqlplus.exe
16:41:25 found SQL*Plus on D:\tools\oracleClient
16:41:25  Statement: 
16:41:25 --------------------------------------------------------------------------
16:41:25 D:\tools\oracleClient\\sqlplus.exe -L ZENKIN_USER1/ZENKIN_USER1@10.254.6.198:1521/NAPFDB @C:\Jenkinserver\workspace\NAPF\NAPF_SERVER_SOURCE/databasescript/NAPF_DBScript.sql --------------------------------------------------------------------------
16:41:25  

I have executed command query, following are the output.

D:\tools\oracleClient>SQLPLUS.EXE ZENKIN_USER1/ZENKIN_USER1@NAPFDB

SQL*Plus: Release 12.2.0.1.0 Production on Thu Dec 21 17:09:14 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Last Successful login time: Thu Dec 21 2017 16:53:41 +05:30

Connected to:
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

SQL> select * from v$version;

BANNER
--------------------------------------------------------------------------------
    CON_ID
----------
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production
         0

PL/SQL Release 12.1.0.2.0 - Production
         0

CORE    12.1.0.2.0      Production
         0

BANNER
--------------------------------------------------------------------------------
    CON_ID
----------
TNS for 64-bit Windows: Version 12.1.0.2.0 - Production
         0

NLSRTL Version 12.1.0.2.0 - Production
         0

**Comment by boaglio** [comment]
fixed, please use new version 1.0.11
