### ISSUE TITLE
Jenkins - Sqlplus script runner plugin - unable to load shared libraries

### ISSUE THREAD

**Issue by vjsandu** [jenkinsci/sqlplus-script-runner-plugin#20]
I am stuck defining LD_LIBRARY_PATH in sqlplus plugin, the same was working without plugin but in shell executor. Now after installing the plugin i have no idea where to define LD_LIBRARY_PATH. please help me out.

![image](https://user-images.githubusercontent.com/30688605/41534181-3805e0aa-731b-11e8-92bc-8a6ff50b2584.png)

**Comment by boaglio** [comment]
LD_LIBRARY_PATH is $ORACLE_HOME/lib where the shared libraries like _libsqlplus.so_ are. Beware of changing this variable because some languages like Python use it too.
