### ISSUE TITLE
Plugin read ö å ä  in weird way and fails the script

### ISSUE THREAD

**Issue by rarawal** [jenkinsci/sqlplus-script-runner-plugin#21]

**Comment by boaglio** [comment]
The plugin needs to check if the end of your file has the **exist** command , otherwise yout Jenkins job will freeze.  I need a sample to understand what is going on...

**Comment by rarawal** [comment]
This works fine if i dont include ö ä å letters.

insertSample.sql
insert into yada
( namn)
(select 'Stö, Äo');
commit;

Run.sql (path of which i am giving in plugin)

-- insert-skript
@"%WORKSPACE%\DB\BuildDB\insertsample.sql";
commit;
exit;

**Comment by rarawal** [comment]
I am closing this  bug as its not sql plug in bug. It was environment issue.
these are the changes required to make this work.
1. Added enviroment variable America_America.UTF8
2. Changed NLS_LANG to America_America.AL32UTF8
Made above changes to server and client machines.
3. Modified jenkins.xml to include UTF8

**Comment by boaglio** [comment]
Good to know, thanks.
