### ISSUE TITLE
Unable to compile Oracle stored procedure upon downloading from GIT using SQL plus Script Runner

### ISSUE THREAD

**Issue by vasu0915** [jenkinsci/sqlplus-script-runner-plugin#22]
Team,
I've downloaded Jenkins and SQL*Plus Script runner plugin to test whether I can compile a stored procedure from GIT repository.  It looks its copying repository from central to local under work space directory but its throwing "SP2-0223: No lines in SQL buffer." error.  When I look at SQL file in the local repository then contents of the file was override with "; Exit". 

Please find log from Jenkins job below and let me know what could be the reason for the above mentioned issue.   

Started by user admin
Building in workspace C:\Program Files (x86)\Jenkins\workspace\Demo4
 > git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url http://test/abc/xyz.git # timeout=10
Fetching upstream changes from http://test/abc/xyz.git
 > git.exe --version # timeout=10
using GIT_ASKPASS to set credentials Test100
 > git.exe fetch --tags --progress http://test/abc/xyz.git +refs/heads/*:refs/remotes/origin/*
 > git.exe rev-parse "refs/remotes/origin/SingleStreamPOC^{commit}" # timeout=10
 > git.exe rev-parse "refs/remotes/origin/refs/heads/SingleStreamPOC^{commit}" # timeout=10
Checking out Revision 8f2bfb4ff9ed0d4056927dca421096a5240b42d7 (refs/remotes/origin/SingleStreamPOC)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 8f2bfb4ff9ed0d4056927dca421096a5240b42d7
Commit message: "- Add enforcer plugin for restricting banned dependencies"
 > git.exe rev-list --no-walk 8f2bfb4ff9ed0d4056927dca421096a5240b42d7 # timeout=10
--------------------------------------------------------------------------
Getting ORACLE_HOME...
Using custom SQL*Plus location
SQL*Plus >>> C:\app\abc123\virtual\product\12.2.0\dbhome_1\bin\sqlplus.exe
Using custom TNS_ADMIN location
TNS_ADMIN >>> C:\app\abc123\virtual\product\12.2.0\dbhome_1\network\admin
--------------------------------------------------------------------------
Using custom ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\app\abc123\virtual\product\12.2.0\dbhome_1
--------------------------------------------------------------------------
Getting SQLPlus version
[Demo4] $ C:\app\abc123\virtual\product\12.2.0\dbhome_1\bin\sqlplus.exe -v

SQL*Plus: Release 12.2.0.1.0 Production

Process exited with status 0
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\app\abc123\virtual\product\12.2.0\dbhome_1
--------------------------------------------------------------------------
Running script C:\Program Files (x86)\Jenkins\workspace\Demo4\DBMS\PACKAGES\Package_Report.sql em TEST/********@ORCL12CPDB
--------------------------------------------------------------------------
[Demo4] $ C:\app\abc123\virtual\product\12.2.0\dbhome_1\bin\sqlplus.exe -L TEST/TEST@ORCL12CPDB "@C:\Program Files (x86)\Jenkins\workspace\Demo4\DBMS\PACKAGES\Package_Report.sql"

SQL*Plus: Release 12.2.0.1.0 Production on Fri Jun 29 11:34:48 2018

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Last Successful login time: Fri Jun 29 2018 11:29:36 -04:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SP2-0223: No lines in SQL buffer.
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
Process exited with status 0
--------------------------------------------------------------------------
Finished: SUCCESS

**Comment by rarawal** [comment]
It looks for exit; at end of script. if you add Exit; at end of script and execute, it works perfectly.

**Comment by vasu0915** [comment]
It worked after I put exit command in the script. Thanks for your help.
