### ISSUE TITLE
Even though we have provided database credentials in the Jenkins configuration, we have to put the credential again in SQL Plus. SQL Plus is not picking the login credentials from Jenkins workspace configuration. Please assist.

### ISSUE THREAD

**Issue by ANI2407rudh** [jenkinsci/sqlplus-script-runner-plugin#23]
Even though we have provided database credentials in the Jenkins configuration, we have to put the credential again in SQL Plus. SQL Plus is not picking the login credentials from Jenkins work space configuration. Please assist.

**Comment by boaglio** [comment]
I didn't get  it. Can you put some screenshots of your situation here ?

**Comment by boaglio** [comment]
Please update to release 2.0.0, now we support _Credentials_ ( thanks to @kinow  \o/ )
