### ISSUE TITLE
SP2-0667: Message file sp1<lang>.msb not found

### ISSUE THREAD

**Issue by debayanchatterjee** [jenkinsci/sqlplus-script-runner-plugin#24]
I have installed sqlplusrunner plugin in Jenkins to execute sql scripts, but I am getting the following error in the log.I have provided correct ORACLE_HOME in Jenkins as well as .bash_profile in server, but the issue is not resolved. Same commands are running fine in server.

runsqlscripts1] $ /oracle/product/12c/12.1.0/bin/sqlplus -L jenkins/Jenkins#132465@psu12g1d @/home/oradeply/.jenkins/workspace/runsqlscripts1/usercreate.sql
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
Process exited with status 1

**Comment by boaglio** [comment]
Please read our Report Problems guide https://wiki.jenkins.io/display/JENKINS/SQLPlus+Script+Runner+Plugin
