### ISSUE TITLE
I have 6 different builds with 6 different database instances and plugin saves only one connection for all builds

### ISSUE THREAD

**Issue by rarawal** [jenkinsci/sqlplus-script-runner-plugin#25]
I have 6 db instances for 6 different builds. I tried giving different instance names aand passwords in each build but it just saves one of the connections.
 - when i change connection string in other build, after save , i can see instance same as before save

**Comment by boaglio** [comment]
I use with 3 different db instances, never had this problem before.  Please [follow the rules to open an issue](https://github.com/jenkinsci/sqlplus-script-runner-plugin) giving more info.

**Comment by rarawal** [comment]
ok, will look into it. As its working for 3 difference instances for you, i will close the bug and try with above rules at my end. In case its not resolved, will open differen bugs. Thanks.
