### ISSUE TITLE
decrypted password

### ISSUE THREAD

**Issue by SrAlmeida** [jenkinsci/sqlplus-script-runner-plugin#27]
Line 17 shows user and password access, is there any way to hide, remove that line or leave as line 14.

- Jenkins server Operation System - Windows 10
- Jenkins version - 2.138
- Where SQLPlus Script Runner is running (local machine or slave machine) - local machine
- Slave machine Operation System (if applicable) - No
- Oracle Database version -Oracle Database 11g Enterprise Edition Release 11.2.0.3.0
- Oracle SQL*Plus version -11.2.0.1.0 
- Build log with debug info enabled.

`Iniciado pelo usuário Matheus Almeida
Construindo no workspace C:\Users\simlam\.jenkins\workspace\BuildSLM
--------------------------------------------------------------------------
Buscando ORACLE_HOME...
Usando local do SQL*Plus customizado
SQL*Plus >>> C:\app\simlam\product\11.2.0\client_1\BIN\sqlplus.exe
Usando TNS_ADMIN customizado
TNS_ADMIN >>> C:\app\simlam\product\11.2.0\client_1\network\admin
--------------------------------------------------------------------------
Usando ORACLE_HOME global
--------------------------------------------------------------------------
Usando ORACLE_HOME =C:\app\simlam\product\11.2.0\client_1
--------------------------------------------------------------------------
Rodando script em etramiteweb/********@DEV-ORASEMA
Script temporário: file:/C:/Users/simlam/.jenkins/workspace/BuildSLM/temp-script-15367868907954635873958652644914.sql
--------------------------------------------------------------------------
[BuildSLM] $ C:\app\simlam\product\11.2.0\client_1\BIN\sqlplus.exe -L etramiteweb/ETRAMITE@DEV-ORASEMA @C:\Users\simlam\.jenkins\workspace\BuildSLM\temp-script-15367868907954635873958652644914.sql

SQL*Plus: Release 11.2.0.1.0 Production on Qua Set 12 18:14:51 2018

Copyright (c) 1982, 2010, Oracle.  All rights reserved.

Conectado a:
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Data Mining and Real Application Testing options

1 linha criada.

  1* INSERT INTO TAB_INFO (VERSAO,DATA_IMPLANTACAO) VALUES ('remover', SYSDATE)
Desconectado de Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Data Mining and Real Application Testing options
Processo terminou com status 0
--------------------------------------------------------------------------
Finished: SUCCESS`

**Comment by boaglio** [comment]
No, sorry. I am not able to handle this information.

**Comment by boaglio** [comment]
Please use _Mask Passwords Plugin_ to hide it.
