### ISSUE TITLE
Build's parameters expansion in "File Script" field

### ISSUE THREAD

**Issue by fpga-tom** [jenkinsci/sqlplus-script-runner-plugin#3]
For parameterized builds I need to be able to expand parameters in "File Script" field. 

the build is parameterized with string parameter DIR (attachment “string_parameter.png”), 
I want to use this parameter in “File Script” (attachment “sqlplus_script_runner.png”)
But in console output the parameter is not expanded (attachment “console_output.png”).

I used this two Javadoc links
http://javadoc.jenkins-ci.org/hudson/model/AbstractBuild.html#getEnvironment(hudson.model.TaskListener)
http://javadoc.jenkins-ci.org/hudson/EnvVars.html#expand(java.lang.String)

I attached two screenshots:
One from github (https://github.com/jenkinsci/sqlplus-script-runner-plugin/blob/master/src/main/java/org/jenkinsci/plugins/sqlplusscriptrunner/SQLPlusRunnerBuilder.java): 
“SQLPlusRunnerBuilder.png” – I highlighted “build.getEnvironment()”
Second, changed lines in “SQLPlusRunnerBuilder.java” – I highlighted “EnvVars env = build.getEnvironment()” and “sqlScript = env.expand(sqlScript)”

So what I need is, to use build parameters in “File Script” field, in “SQLPlus Script Runner Plugin” form. (I attached screenshot “what_i_need.png”).

![string_parameter](https://cloud.githubusercontent.com/assets/992893/21016424/c195fdb8-bd65-11e6-9058-e986d5a1b6a4.png)
string_parameter.png

![sqlplus_script_runner](https://cloud.githubusercontent.com/assets/992893/21016421/c1935e50-bd65-11e6-83b2-7d227b40399b.png)
sqlplus_script_runner.png

![console_output](https://cloud.githubusercontent.com/assets/992893/21016420/c19271fc-bd65-11e6-9c81-0aa0912eb581.png)
console_output.png

![sqlplusrunnerbuilder](https://cloud.githubusercontent.com/assets/992893/21016425/c19912c8-bd65-11e6-8b46-b429dbee570a.png)
SQLPlusRunnerBuilder.png

![sqlplusrunnerbuilderchanged](https://cloud.githubusercontent.com/assets/992893/21016423/c1949068-bd65-11e6-86ee-9cb49d024bdc.png)
SQLPlusRunnerBuilderChanged.png

![what_i_need](https://cloud.githubusercontent.com/assets/992893/21016422/c193efaa-bd65-11e6-8ef2-467aa81c46a2.png)
what_i_need.png

**Comment by boaglio** [comment]
Fixed in release 1.0.4, thank you.
