### ISSUE TITLE
Not able to execute as a step on a slave nodes

### ISSUE THREAD

**Issue by haroldo-bonette** [jenkinsci/sqlplus-script-runner-plugin#30]
When the stage runs on slave nodes I get an error Error:Process working directory 'E:\jenkins\jobs\SIEBEL-DEV1\builds\53' doesn't exist!
It seems the plugin is looking for "jobs" folder on slave and that folder exists only on master.
It runs fine on master.

pipeline {
   agent none
    stages {
        stage('Build'){
            agent { label 'slave' }
            steps{
                echo "${NODE_NAME}"
                echo 'SQLPlusRunner running user define script for system@xe'
                step([$class: 'SQLPlusRunnerBuilder',credentialsId:'ID', instance:'DBINST', scriptType:'userDefined', script: '', scriptContent:'select * from v$version'])
            }
        }
    }
}

**Comment by boaglio** [comment]
Fixed on release 2.0.2

**Comment by haroldo-bonette** [comment]
I have updated it to 2.0.2 and when it runs on slave it gives a null pointer exception:

00:00:03 java.lang.NullPointerException
00:00:03 	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.isWindowsOS(SQLPlusRunner.java:577)
00:00:03 	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:269)
00:00:03 	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:174)
00:00:03 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
00:00:03 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
00:00:03 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
00:00:03 	at hudson.security.ACL.impersonate(ACL.java:290)
00:00:03 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
00:00:03 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
00:00:03 	at java.util.concurrent.FutureTask.run(Unknown Source)
00:00:03 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
00:00:03 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
00:00:03 	at java.lang.Thread.run(Unknown Source)

**Comment by boaglio** [comment]
Please try release 2.0.3

**Comment by haroldo-bonette** [comment]
I get this exception now:

10:30:46 java.lang.ClassCastException: org.jenkinsci.plugins.workflow.job.WorkflowRun cannot be cast to hudson.model.AbstractBuild
10:30:46 	at org.jenkinsci.plugins.sqlplus.script.runner.FileUtil.createTempScript(FileUtil.java:86)
10:30:46 	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:278)
10:30:46 	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:174)
10:30:46 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
10:30:46 	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
10:30:46 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
10:30:46 	at hudson.security.ACL.impersonate(ACL.java:290)
10:30:46 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
10:30:46 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
10:30:46 	at java.util.concurrent.FutureTask.run(Unknown Source)
10:30:46 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
10:30:46 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
10:30:46 	at java.lang.Thread.run(Unknown Source)

**Comment by boaglio** [comment]
I need more details about your Jenkins version, your master OS and Slave OS please.

**Comment by haroldo-bonette** [comment]
Here it goes:
Jenkins: 2.138.1
Master: Windows 2012 R2
Slave: Windows 2012 R2

PS: on master still running fine.

**Comment by boaglio** [comment]
Maybe your Slave client is old... this upgrade should work for Jenkins 2.73.3+ .
Please try to do these steps:

1. Stop your Jenkins slave agent;
2. Rename your slave directory to **E:\jenkins-old\**;
3. Start  your Jenkins slave agent.

**Comment by haroldo-bonette** [comment]
Still the same issue.

**Comment by boaglio** [comment]
Please try release 2.0.4

**Comment by haroldo-bonette** [comment]
It works like a charm now Fernando. thanks
