### ISSUE TITLE
Plugin does not support as SYSDBA

### ISSUE THREAD

**Issue by bryan-tolbert** [jenkinsci/sqlplus-script-runner-plugin#31]
Accepted:

C:\app\Administrator\product\12.2.0\dbhome_1\bin\sqlplus.exe **-L / as sysdba** @C:\Users\Administrator\test.sql

Did not Accept:

 C:\app\Administrator\product\12.2.0\dbhome_1\bin\sqlplus.exe **-L sysdba/@** @C:\Users\Administrator\test.sql

**Comment by boaglio** [comment]
No it doesn't... now I am too busy to create an option "as SYSDBA" or "as SYSOPER". Fell free to code it and send a Pull Request.
