### ISSUE TITLE
Plugin doesn't consider special characters

### ISSUE THREAD

**Issue by 4lex4nolr** [jenkinsci/sqlplus-script-runner-plugin#33]
RHEL Server 7.5
Jenkins ver. 2.155
SQLPlus Script Runner is running in local machine
Slave machine Operation System is Oracle Linux Server 7.4
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
SQL*Plus: Release 12.2.0.1.0 Production

17:29:54 [CHECK] $ /usr/local/sbin/sqlplus -L user/password@host:port/SID @/path/to/file/v.$install.test_view.sql
17:29:54 
17:29:54 SQL*Plus: Release 12.2.0.1.0 Production on Thu Dec 13 17:29:54 2018
17:29:54 
17:29:54 Copyright (c) 1982, 2016, Oracle.  All rights reserved.
17:29:54 
17:29:54 Last Successful login time: Thu Dec 13 2018 17:29:16 +03:00
17:29:54 
17:29:54 Connected to:
17:29:54 Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
17:29:54 
17:29:54 SP2-0310: unable to open file "/path/to/file/v.$install.test_view.sql"
17:29:54 SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
17:29:54 Process exited with status 0
17:29:54 --------------------------------------------------------------------------

There are files that contain special characters (i.e. $, #) in the name, and this plugin cannot find them.

**Comment by boaglio** [comment]
Hi Aleksander,

Unfortunately this is not my plugin issue, it is an Oracle SQL*Plus limitation. 

```
# cat v.\$install.test_view.sql 
select * from v$version;

exit;
# sqlplus fb/fb@xe @ v.\$install.test_view.sql 

SQL*Plus: Release 12.1.0.1.0 Production on Sun Dec 16 08:29:13 2018

Copyright (c) 1982, 2013, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SP2-0310: unable to open file "v.$install.test_view.sql"
SQL> 
```
Sorry... =(
