### ISSUE TITLE
Unable to connect when password has @ symbol

### ISSUE THREAD

**Issue by Ramesh-V-R** [jenkinsci/sqlplus-script-runner-plugin#36]
When the password contains @ symbol, could not resolve connection appears. With other passwords, t works fine.
--
Jenkins server Operation System; Windows 7 enterprise
Jenkins version ; 2.150.2
Where SQLPlus Script Runner is running (local machine or slave machine); local
Slave machine Operation System (if applicable); NA
Oracle Database version; 11.2.0 / 11g32bit
Oracle SQL*Plus version; SQL*Plus: Release 11.2.0.1.0 Production

Build log with debug info enabled.
[QA_DB_Flush_ConnectionPool] $ C:\Oracle\client11g32bit\product\11.2.0\client_1\bin\sqlplus.exe -L SPIVA/"h8L2He@K"@AWS_QA_DR1 @C:\Users\ramesh_r\softwares\apache-tomcat-8.0.36\temp\temp-script-15488411508681155976248386357572.sql
 
SQL*Plus: Release 11.2.0.1.0 Production on Wed Jan 30 04:39:12 2019
 
Copyright (c) 1982, 2010, Oracle.  All rights reserved.

ERROR:
ORA-12154: TNS:could not resolve the connect identifier specified
SP2-0751: Unable to connect to Oracle.  Exiting SQL*Plus

**Comment by boaglio** [comment]
Sorry, this is a SQL*Plus issue, not a plugin issue.
