### ISSUE TITLE
Jenkins loses "Set global ORACLE_HOME" on save

### ISSUE THREAD

**Issue by jansenm** [jenkinsci/sqlplus-script-runner-plugin#38]
The plugin is configured with global ORACLE_HOME, TNS_ADMIN and sqlplus location. The settings are persisted to the configuration file.

On reopening "Jenkins > Configuration" the values for TNS_ADMIN and sqlplus location are prefilled. The ORACLE_HOME one isn't so that on save the settings gets unset.

That is unexpected and a problem because when changing something unrelated you break your sqlplus jobs.

Jenkins ver. 2.164.3
Script Runner 2.0.6

**Comment by boaglio** [comment]
Fixed, please try version **2.0.7** .
