### ISSUE TITLE
"Try to detect ORACLE_HOME" doesn't work as expected

### ISSUE THREAD

**Issue by jansenm** [jenkinsci/sqlplus-script-runner-plugin#39]
ORACLE_HOME is set as a global Jenkins Variable under "Jenkins > Configuration". It shows up in the builds "Environment Variables" listing.

Still the plugin is unable to detect ORACLE_HOME from the environment variable. The build fails.

Jenkins ver. 2.164.3
Script Runner 2.0.6

With this and Bug #38 the plugin is completely broken for us. We have to configure the oracle client in each and every job.

**Comment by boaglio** [comment]
ORACLE_HOME is from your OS, not from Jenkins. This plugin is just a SQL*Plus wrapper... if you don't have ORACLE_HOME defined, running _sqlplus_ on command won't work.  I've just added this feature to also check on Jenkins global variables, please try version **2.0.7** .
