### ISSUE TITLE
Sqlplus Runner status is incorrect.

### ISSUE THREAD

**Issue by dvhegde** [jenkinsci/sqlplus-script-runner-plugin#4]
My sqlplus script tries to drop a non-existing table and exits with a non-zero error code. However, SQLPlus runner ignores the fact that the script exited with the non-zero error code and marks the build as successful. The build should be marked as Failed because the script exited with error code of 174 which is non-zero, correct?

Here are the version numbers of the various components 
Web Application Server:  Tomcat 8.0.20
![sqlplus runner wrong status - console output](https://cloud.githubusercontent.com/assets/13725350/22030939/08ecff7a-dc94-11e6-93e4-1f885f8f6a58.png)

JDK Version:                    1.8.0_51
Jenkins Version:               1.651.3
SQLPlus Runner Version:  1.0.2
****

**Comment by boaglio** [comment]
Fixed in release 1.0.4, thank you.

**Comment by dvhegde** [comment]
Yes, it works fine now. Thanks.
