### ISSUE TITLE
Invalid Credentials after moving credentials to a Folder

### ISSUE THREAD

**Issue by haroldo-bonette** [jenkinsci/sqlplus-script-runner-plugin#41]
It seems the plugin is not able to retrieve credentials if they are located inside a folder. After we moved all credentials to a Folder the step for SQLPlus plugin stopped working with error "Failed to initialize credentials or load user and pass"

Credentials path: Jenkins > FOLDER_NAME > Credentials > Folder > Global credentials (unrestricted)

Jenkins server Operation System:Win
Jenkins version: 2.176.1
Where SQLPlus Script Runner is running : slave;
Slave machine Operation System: Windows;
Oracle Database version 12.01;
Oracle SQL*Plus version: 12.2.0.1.0;

ERROR: Invalid credentials TEST_DB_ADMIN. Failed to initialize credentials or load user and pass

Pipeline: step([$class: 'SQLPlusRunnerBuilder',credentialsId:"${ADMIN_DB_CRED}", instance:"${ENV_DSN}", scriptType:'userDefined', script: '', scriptContent:"SELECT * FROM TABLE"])

I also tried with freestyle project and I was able to select the credentials but the build also failed with same error.

**Comment by boaglio** [comment]
Hi Haroldo, I don't have any control over this, when I get Jenkins credentials I use  _CredentialsMatchers.withId(credentialsId)_ , so maybe you should test using these values as credentialsId:  

- FOLDER_NAME/TEST_DB_ADMIN 
- FOLDER_NAME//TEST_DB_ADMIN 
- FOLDER_NAME\TEST_DB_ADMIN 
- FOLDER_NAME\\TEST_DB_ADMIN 

And also check if there is any restriction access to this credential.

**Comment by haroldo-bonette** [comment]
Hi Fernando, thanks for the quick reply.
I tried to use the folder name in the credentials Id but it does not work.
From a quick research it seems this method will lookup only the global scope whether with Folder plugin the credentials will have a different scope, maybe [this](https://github.com/jenkinsci/gitlab-plugin/issues/631#issuecomment-335107113) could help to find a way to make the plugin lookup folder scope credentials...

**Comment by boaglio** [comment]
I couldn't find a way, sorry... if you find it please send a pull request.

**Comment by cmaggiulli** [comment]
@haroldo-bonette I'm going to attempt to resolve this
