### ISSUE TITLE
Unable to use dynamic user/pass values without credentials

### ISSUE THREAD

**Issue by UnicornSnuggler** [jenkinsci/sqlplus-script-runner-plugin#42]
The latest update enabled the use of credentials, but it also removed the use of dynamic username and password entry in the event that no credentials exist.  We're trying to pull usernames and passwords from HashiCorp Vault to make connections to our Oracle databases and we'd prefer not to use credentials so that we don't have to keep manually updating them every time the vault secrets change.  Is there any way you could reimplement this user/pass functionality?  Optimally, there would be some sort of direct Vault integration, but that seems a bit overkill.

Thanks in advance!

**Comment by boaglio** [comment]
Hi @PorkchopDonut , you should try [Jenkins Vault Plugin](https://plugins.jenkins.io/hashicorp-vault-plugin).

**Comment by UnicornSnuggler** [comment]
The Jenkins Vault Plugin doesn’t solve the problem I’m talking about... We could pass tons of Vault credentials into this job but the fact of the matter is that we wouldn’t be able to dynamically use them for SQLPlusRunner connection strings unless you reenabled the user/pass functionality. Those Vault credentials are of no use to us if we can’t pass them in somehow as your plugin only works with Jenkins credentials now.

**Comment by boaglio** [comment]
You should keep running with an old version then , [credentials support was implemented a long time ago](https://wiki.jenkins.io/display/JENKINS/SQLPlus+Script+Runner+Plugin).

**Comment by UnicornSnuggler** [comment]
We tried rolling back to the last 1.x release of your plugin and it was crashing on the 2.x version of Jenkins we’re running. I’m assuming there’s some sort of incompatibility between the versions. Are you saying that you’re unwilling to reimplement user/pass functionality?

**Comment by boaglio** [comment]
Yes, credentials support wasn't only a feature, was a security issue to safely handle passwords.
