### ISSUE TITLE
Change credentials dynamically

### ISSUE THREAD

**Issue by goswings** [jenkinsci/sqlplus-script-runner-plugin#45]
Hi, May I check with you if I want to change the credentials dynamically is possible?

**Comment by boaglio** [comment]
If you write a logic in your Pipeline script to change your credentials dynamically, it should work.
Check a pipeline sample script at documentation page: https://plugins.jenkins.io/sqlplus-script-runner

**Comment by goswings** [comment]
Hi Boaglio, 
Sorry, I don't quit understand, May I know the class is Job name?
If yes, show error is no known implementation of interface jenkins.tasks.SimpleBuildStep is named testDB..if No, can share the sample to me? thanks 

![image](https://user-images.githubusercontent.com/26316763/67190278-42e6d400-f422-11e9-81c3-790409b8a8ec.png)

![image](https://user-images.githubusercontent.com/26316763/67190445-8f321400-f422-11e9-830b-4c8fff3aac49.png)

**Comment by boaglio** [comment]
**Class** parameter you can't change, you should do it on **credentialsId** .

So your environment could have two credentials:  _mydb_dev_ (for development) and _mydb_prod_ (for production).

This is my untested sample: 

```
node {
         if (env.ENV_NAME == 'development') {

                echo 'Updating development database...'
                step([$class: 'SQLPlusRunnerBuilder',credentialsId:'mydb_dev', instance:'xe',scriptType:'file', script: 'start.sql',scriptContent: ''])

          } else {

                echo 'Updating production database...'
                step([$class: 'SQLPlusRunnerBuilder',credentialsId:'mydb_prod', instance:'xe',scriptType:'file', script: 'start.sql',scriptContent: ''])

          }
  
}
```

**Comment by goswings** [comment]
Hi Boaglio, very very thanks for your help.

**Comment by AmanDhaka1986** [comment]
Hi Boaglio,  I am trying the same but fetching the file from github , but credentials takes either github or DB, one example where i can use github as SCM and then deploy ? i am bit new to jenkins hence struggling with this pipeline code. Please suggest.
