### ISSUE TITLE
how to make sqlplus script runner support chinese in database?

### ISSUE THREAD

**Issue by carrisonj** [jenkinsci/sqlplus-script-runner-plugin#47]
sqlplus script runner works fine,but Ifound

**Comment by boaglio** [comment]
Please  inform:

    Jenkins server Operation System;
    Jenkins version;
    Where SQLPlus Script Runner is running (local machine or slave machine);
    Slave machine Operation System (if applicable);
    Oracle Database version;
    Oracle SQL*Plus version;
    Build log with debug info enabled.

**Comment by boaglio** [comment]
Lack of information, closing issue.
