### ISSUE TITLE
Parameter based SQL Script

### ISSUE THREAD

**Issue by ipvinay** [jenkinsci/sqlplus-script-runner-plugin#49]
HI Team,
Do we support parameter based sqlScript runner, wher we used script type as file. ?
Example:
	scriptType:'file', 
		script: 'createoracle_owner.sql ${SCHEMA_OWNER} ${SCHEMA_ROLE}',
		scriptContent:'',

**Comment by boaglio** [comment]
Not yet, fell free to submit a pull request with this feature.
