### ISSUE TITLE
ORA-00955 On CREATE TABLE script

### ISSUE THREAD

**Issue by CGarces** [jenkinsci/sqlplus-script-runner-plugin#50]
In using  sqlplus-script-runner-plugin 2.0.9 over oracle autonomous database 19.

My pipeline is

```
node {
  stage('SCM') {
    git url: 'https://github.com/CGarces/test_SQLPlusRunnerBuilder'
  }
  stage('Creacion tablas') {
	step([$class: 'SQLPlusRunnerBuilder',credentialsId:'pwd_ddbb', instance:'db202005092134_low',scriptType:'file', script: 'resources/ddl/creates/tablas/tabla_ejemplo.sql',scriptContent: ''])
  }
}
```
SQLPlusRunnerBuilder execute one file, inside the repo, that contains a CREATE TABLE sentence.

Expected behaviour
-Pipeline works without errors

Current behaviour
- The table is created (https://github.com/CGarces/test_SQLPlusRunnerBuilder/blob/master/full_log.txt#L66)
- I get ORA-00955 and pe pipeline fails https://github.com/CGarces/test_SQLPlusRunnerBuilder/blob/master/full_log.txt#L72

Looks like the script is executed twice?

To reproduce the error.

Create a pipeline from
https://github.com/CGarces/test_SQLPlusRunnerBuilder/blob/master/Jenkinsfile
Check that there is no table `tabla_ejemplo` on the default schema and launch the build.

**Comment by boaglio** [comment]
Hi @CGarces ,

Nice report, I think I found the problem, it is not related to this plugin.

This is your script:

```
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE tabla_ejemplo (
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
);
/
```

When SQL*Plus finds **";"** it runs a _CREATE TABLE_,  and then with **"/"** it runs again.

You can try this way:

```
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE tabla_ejemplo (
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
)
/
```

I will close this issue, if you have problems you can reopen. 

Thanks. 

```

**Comment by CGarces** [comment]
Thanks, what stupid mistake.
I'll try my scripts on sqlcli before blame the plugin again.
