### ISSUE TITLE
Error "TNS:could not resolve the connect identifier specified" when there's a "@" in password

### ISSUE THREAD

**Issue by shiaohuihoh** [jenkinsci/sqlplus-script-runner-plugin#52]
Hi,
Is there a way to pass in password with a "@" within the password.
I'va set the username and password accordingly.
Below is the output in console.
Thanks.

--------------------------------------------------------------------------
 
[SQL_TEST] $ C:\Oracle\instantclient_19_6\sqlplus.exe -L dwhapex/Welcome@2020@ofcadwdev_high @C:\Users\vicc75a\AppData\Local\Temp\temp-script-15921993183494695056065416170093.sql

SQL*Plus: Release 19.0.0.0.0 - Production on Mon Jun 15 15:35:18 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-12154: TNS:could not resolve the connect identifier specified

SP2-0751: Unable to connect to Oracle.  Exiting SQL*Plus
Process exited with status 1

**Comment by boaglio** [comment]
Hello, please try release 2.0.12 .
