### ISSUE TITLE
Hide connection-string

### ISSUE THREAD

**Issue by ChrisR69** [jenkinsci/sqlplus-script-runner-plugin#53]
When I have a look into the console-output I see the following
```
Running defined script on <user>/********@<SID>
...
${ORACLE_HOME}/bin/sqlplus -L <user>/<password>@<SID> "@<PATH>/temp-script-16008850482646130697981091368123.sql"
```

So we are able to see the password.
I had the same issue in my production-environment with my scripts and I solved it like this.
There is a script login.sql that contains connect <user>/<password>@<SID>
And I use
```
 sqlplus -s -l /NOLOG @login.sql <<EOF
@myScript.sql
EXIT
EOF
```
The -s and -l is not important.

For **scriptType** the solution is quiet eays to add the connection-string at the beginning of the tempScript.
```
+ String connectionString = "connect " + user + SLASH + DOUBLE_QUOTES + password + DOUBLE_QUOTES + AT + instanceStr;
- scriptFilePath = FileUtil.createTempScript(build, workspace, script, slaveMachine);
+ scriptFilePath = FileUtil.createTempScript(build, workspace, connectionString, script, slaveMachine);

```
and in public static FilePath createTempScript(...)

```
+ filePath.write(connectionString + "\n", StandardCharsets.UTF_8.name());
filePath.write(content, StandardCharsets.UTF_8.name());

```
If you use a file it is more complicated.

**Comment by boaglio** [comment]
You should use **Mask Passwords** plugin , please read the [documentation](https://plugins.jenkins.io/sqlplus-script-runner/).
