### ISSUE TITLE
Enhance Fileutil.hasExitCode

### ISSUE THREAD

**Issue by ChrisR69** [jenkinsci/sqlplus-script-runner-plugin#54]
There is
```
		if (lastLine.trim().equalsIgnoreCase(SQLPLUS_EXIT))
			found = true;

```
But we also can use
`EXIT 1`
or 
```
VARIABLE result NUMBER
BEGIN
  :result := 1;
END;
/
EXIT :result
```

So I recommend to add a new check
```
		if (lastLine.trim().toUpperCase().startsWith("EXIT "))
			found = true;
```

**Comment by boaglio** [comment]
Nice one, I will do it soon or if you want you can send a pull request.

**Comment by boaglio** [comment]
Actually I can't do this... since [EXIT can reference a FOR LOOP](https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/exit_statement.htm#LNPLS01318), I can't check **"EXIT "** for a valid exit for SQL*Plus. 
Sorry.
