### ISSUE TITLE
parse/retrieve output

### ISSUE THREAD

**Issue by martens-d** [jenkinsci/sqlplus-script-runner-plugin#56]
Hello,
is there a way to parse the output of a script, store it in a variable or save to file?

We are running quality control over the DB and the results are stored in a table. All I need is a way to retrieve the data and check for a successful test.

Thanks

**Comment by boaglio** [comment]
You can use **SQL*Plus spool** to output to a file:

https://docs.oracle.com/cd/B19306_01/server.102/b14357/ch12043.htm
http://www.dba-oracle.com/t_sqlplus_spool.htm
