### ISSUE TITLE
Substitution variables not working with external script

### ISSUE THREAD

**Issue by cmaggiulli** [jenkinsci/sqlplus-script-runner-plugin#58]
Jenkins server Operation System: Debian on EC2
Jenkins version: Amazon Linux on EC2
Where SQLPlus Script Runner is running (local machine or slave machine); Worker node
Slave machine Operation System (if applicable); , Amazon Linux on EC2 as EC2 instance using the EC2 plugin
Oracle Database version; 11g
Oracle SQL*Plus version; 

Summary:

I have the following Code

```
step([
   $class: 'SQLPlusRunnerBuilder',
   credentialsId:'sis-database-prod-schema', 
   instance:"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=db_${ENVIRONMENT}.int.excelsior.edu)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=${ENVIRONMENT})))",
   scriptType:'file', 
   script: "schedule-instructor-evals.sql ${DEBUG_FLAG}",
   customOracleHome: '/usr/lib/oracle/12.2/client64'
])
```

Notice that we are sending `DEBUG FLAG` into the schedule-instructor-evals.sql.  In the schedule-instructor-evals.sql file we reference `DEBUG_FLAG` as a substitution parameter

`CALL prod.sis_faculty_evals.scheduleInstuctorEvals('&1');`

When I run the pipeline it fails with the following error

```
SQL*Plus exec file  = sqlplus
SQL*Plus directory: /usr/lib/oracle/12.2/client64/bin
[sis-email-faculty-cornerstone-course] $ /usr/lib/oracle/12.2/client64/bin/sqlplus -L ******** "@/home/ec2-user/workspace/sis/database/sis-email-faculty-cornerstone-course/sis-email-faculty-cornerstone-course/sis-email-faculty-cornerstone-course.sql Y"

SQL*Plus: Release 12.2.0.1.0 Production on Fri Jan 22 15:38:46 2021

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Last Successful login time: Fri Jan 22 2021 15:36:23 +00:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SP2-0310: unable to open file "/home/ec2-user/workspace/sis/database/schedule-instructor-evals.sql Y"
SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
Process exited with status 0
```

As you can see, it's attempting to open up the file "/home/ec2-user/workspace/sis/database/schedule-instructor-evals.sql Y" and not treating the Y ( DEBUG_FLAG ) as a substitution variable.

Here is how it works with the same exact setup, but calling sqlplus from the commandline

`sqlplus prod/******@db_test:1521/test @schedule-instructor-evals.sql Y`

Produces the following output

```
SQL*Plus: Release 12.1.0.1.0 Production on Fri Jan 22 11:51:20 2021

Copyright (c) 1982, 2013, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

old   1: CALL prod.sis_faculty.schedule-instructor-evals.sql('&1')
new   1: CALL prod.sis_faculty.schedule-instructor-evals.sql('Y')

Call completed.

Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
```

If you want I can fix this as a pull request

**Comment by cmaggiulli** [comment]
I found a workaround using the following code

`script: "schedule-instructor-evals.sql\" \"${DEBUG}"`

**Comment by AmanDhaka1986** [comment]
could you please provide the entire pipeline code if possible,
