### ISSUE TITLE
running sql with runtime variable passing(sqlplus script runner)

### ISSUE THREAD

**Issue by AmanDhaka1986** [jenkinsci/sqlplus-script-runner-plugin#59]
i have to run a sql in a schema which needs to be passed in run time either one variable should be passed in credentials :- username or , during the execution the script should go like 👎 
conn adminAccount[SCHEMA_NAME]/**********@DV_DBB;    --------- here schema name should be passed as runtime or as variable and this variable should be somhow passed via git code.
Main.sql. ----- this script shuld be picked by github.

Anyone has done this or any idea or pointer please ?

**Comment by boaglio** [comment]
This is weird, you have a lot of users with the same password ? Anyway, you can check Jenkins documentation regarding Credentials:  https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#handling-credentials

Since you are looking for a generic way to run a script, maybe you can solve your problem not in Jenkins, but in your database by create a common schema accessible by the others.

**Comment by AmanDhaka1986** [comment]
i am trying to develop pipeline for developers so that they can deploy in any schema for that in Oracle we can use proxy login like :-     conn adminschema[Actual_schema]/password@conenctionstring , so for this the adminschema will remain same so does passsword only actual_schema will change for every user when they commit there changes, so the adminschema/password can be stored somewhere in jenkins and can pass actual_schema i am trying.

**Comment by boaglio** [comment]
So I think you have an easy way to this by database only... you can connect with an admin user and create/update objects from other schemas.  Change your script to get a parameter from the target schema.

https://blogs.oracle.com/opal/sqlplus-101-substitution-variables#9_2

**Comment by AmanDhaka1986** [comment]
this wil expose password in script mate , not a viable solution.

**Comment by boaglio** [comment]
No, you won't connect with your target schema, you will use an admin credentials to connect and then in your script update other user's objects.

Something like this:

1. connect system@*** (connect DBA user using Jenkins Credentials);
2. pass DEV1 (valid schema) to your script;
3. inside your script do some DML like:  UPDATE DEV1.mytable SET upd_date=sysdate where ID=1;

**Comment by AmanDhaka1986** [comment]
Thanks, but this is not our intent , many stored procs and triggers can't work with schema name as prefix before object that is the reason i am trying the proxy login or actual login into schema's. For the time being i am creating multiple jobs per schema basis as did not found any way to pass on this on the fly.
