### ISSUE TITLE
Script doesn't end.

### ISSUE THREAD

**Issue by grifenpierre** [jenkinsci/sqlplus-script-runner-plugin#6]
When i run a simple querry with the plug in it achieve to connect the database base but the script seem to loop and never close.

**Comment by grifenpierre** [comment]
i'm on windows 7 pro N
jenkins is on version 2.46.1
sqlplus is on version 10.2.0.4.0
and the console output lock this way

Démarré par l'utilisateur pierrick
Building in workspace C:\Program Files (x86)\Jenkins\workspace\oracle
\--------------------------------------------------------------------------
Getting ORACLE_HOME...
\--------------------------------------------------------------------------
Using custom ORACLE_HOME
\--------------------------------------------------------------------------
Using ORACLE_HOME =D:\tools\oracle\product\10.2.0\client_1
\--------------------------------------------------------------------------
Getting SQLPlus version
Process exited with status 0
\--------------------------------------------------------------------------

SQL*Plus: Release 10.2.0.4.0 - Production

\--------------------------------------------------------------------------
Using ORACLE_HOME =D:\tools\oracle\product\10.2.0\client_1
\--------------------------------------------------------------------------

Running defined script on annuaire/********@DEV2
Temp script:C:\windows\TEMP\temp-script-14932140685903509814193422551450.sql
\--------------------------------------------------------------------------

**Comment by boaglio** [comment]
I think there is something to do with your script , please try a simple example like _select * from v$version;_ and try running with SQL*Plus by command line too.
