### ISSUE TITLE
Custom TNS_Admin not working

### ISSUE THREAD

**Issue by karthikeyan82** [jenkinsci/sqlplus-script-runner-plugin#60]
The plugin is working great. However The plugin is not picking the Custom_TNS Admin path. It always looks for TNSNAMES.ORA file in /usr/lib/oracle/21/client64/network/admin path. 

It appears like Custom_TNS Admin is ignored. Can you please help?

**Comment by karthikeyan82** [comment]
DETAILS:
----------
Jenkins server Operation System; - Linux
Jenkins version ; - CloudBees Jenkins Enterprise 2.263.4.1-rolling
Where SQLPlus Script Runner is running (local machine or slave machine); - slave
Slave machine Operation System (if applicable); - Linux
Oracle Database version; - Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
Oracle SQL*Plus version; - SQL*Plus: Release 21.0.0.0.0 - Production
Build log with debug info enabled.

SQL*Plus: Release 21.0.0.0.0 - Production on Fri Mar 26 17:36:57 2021
Version 21.1.0.0.0

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

Last Successful login time: Fri Mar 26 2021 17:36:57 -07:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
--------------------------------------------------------------------------
Getting ORACLE_HOME...
Using custom SQL*Plus location
SQL*Plus directory: /bin/sqlplus
Using custom TNS_ADMIN location
TNS_ADMIN: /apps/jenkins-agent/workspace/HP-BIO-SNAP/DeployScripts
--------------------------------------------------------------------------
Using custom ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =/usr/lib/oracle/21/client64
--------------------------------------------------------------------------
Getting SQLPlus version
[DeployScripts] $ /bin/sqlplus -v

SQL*Plus: Release 21.0.0.0.0 - Production
Version 21.1.0.0.0

Process exited with status 0
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Using ORACLE_HOME =/usr/lib/oracle/21/client64
--------------------------------------------------------------------------
Running defined script on csar_ADM/********@csard02r.pldc.kp.org
Temp script: file:/apps/jenkins-agent/workspace/HP-BIO-SNAP/DeployScripts/temp-script-16168054177712861960270607265292.sql
--------------------------------------------------------------------------
[DeployScripts] $ /bin/sqlplus -L ******** @/apps/jenkins-agent/workspace/HP-BIO-SNAP/DeployScripts/temp-script-16168054177712861960270607265292.sql

SQL*Plus: Release 21.0.0.0.0 - Production on Fri Mar 26 17:36:57 2021
Version 21.1.0.0.0

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

ERROR:
ORA-12154: TNS:could not resolve the connect identifier specified


SP2-0751: Unable to connect to Oracle.  Exiting SQL*Plus
Process exited with status 1
--------------------------------------------------------------------------
Exit code : 1
--------------------------------------------------------------------------
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:551)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:195)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Process exited with error
Gitcolony notification failed - java.lang.IllegalArgumentException: Invalid url: 
Finished: FAILURE
REST API

**Comment by boaglio** [comment]
The only thing _CUSTOM_TNS_ADMIN_ does is to define _TNS_ADMIN_ env variable for SQL*Plus.

I haven't tested with version 21, have you tried to run it manually ? 

```
$ export TNS_ADMIN=/apps/jenkins-agent/workspace/HP-BIO-SNAP/DeployScripts
$ /bin/sqlplus -L ******** @/apps/jenkins-agent/workspace/HP-BIO-SNAP/DeployScripts/temp-script.sql
```

**Comment by karthikeyan82** [comment]
Thanks for your email.



I tried setting export TNS_ADMIN and ran the sqlplus manually. It works perfectly fine

However it is not working only with the plug-in. I also tried to setting TNS_ADMIN outside of the plug-in and tried running. Still the plugin looks for Tnsnames.ora file from default location (/usr/lib/oracle/21/client64
). Please see the attached document with DEBUG mode. I have highlighted where it looks in default location (instead of custom location)

Can you please help?

**Comment by boaglio** [comment]
I've just found a bug, please try new version 2.0.16.

**Comment by karthikeyan82** [comment]
Thank you. I could see version 2.0.16 in Github. However in Jenkins, it is still showing old version 2.0.15.

So, I could not install 2.0.16 through Jenkins. Is there any other way to install the latest version?

**Comment by boaglio** [comment]
I think you will be able to update automatically in a few hours/days.
However, if you want to try it now you can [upload it manually](https://www.jenkins.io/doc/book/managing/plugins/).

**Comment by karthikeyan82** [comment]
Thank you. The issue is fixed with 2.0.16

**Comment by karthikeyan82** [comment]
I got a quick question

While there is error in the db script (say syntax error), the script execution will fail and sql plus will exit

However I want to catch the error and fail the pipeline. No further steps should execute if sql plus plug-in detects an syntax or any ORA error.

I could find the info in the Jenkins documentation. Can you pls help?

**Comment by boaglio** [comment]
Maybe you can [force SQL * Plus to return something other than zero](https://www.unix.com/unix-for-advanced-and-expert-users/161680-how-make-sql-plus-exit-error-code.html).
