### ISSUE TITLE
Problems using the plugin for the first time

### ISSUE THREAD

**Issue by fabiofetter** [jenkinsci/sqlplus-script-runner-plugin#61]
Ok, I'm probably doing something wrong... 
I just add the plugin and I'm trying to test it. 

Jenkins server Operation System: Linux XXXX 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Jenkins version: Jenkins 2.289.2
Where SQLPlus Script Runner is running (local machine or slave machine): local
Oracle Database version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
Oracle SQL*Plus version: SQL*Plus: Release 12.2.0.1.0 Production on Fri Aug 20 15:17:53 2021
Build log with debug info enabled:
Running as SYSTEM
Building in workspace /home/jenkins/.jenkins/workspace/CheckData/Porque_um_artigo_nao_aparece_no_SMPT
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
--------------------------------------------------------------------------
Getting ORACLE_HOME...
[DEBUG] Global SQL*Plus selected
--------------------------------------------------------------------------
Using global SQL*Plus location
Using custom TNS_ADMIN location
TNS_ADMIN: /apps/jenkins/dbase/instantclientORACLE_12_2/tnsnames.ora
[DEBUG] Global ORACLE_HOME selected
--------------------------------------------------------------------------
Using global ORACLE_HOME
detected host  = pjenkins01.pt.corp.leroymerlin.com
slave machine: false
--------------------------------------------------------------------------
Using ORACLE_HOME =/apps/jenkins/dbase/instantclientORACLE_12_2
--------------------------------------------------------------------------
Getting SQLPlus version
[DEBUG] ORACLE_HOME = /apps/jenkins/dbase/instantclientORACLE_12_2
[DEBUG] LD_LIBRARY_PATH  = /apps/jenkins/dbase/instantclientORACLE_12_2/lib
SQL*Plus exec file  = sqlplus
--------------------------------------------------------------------------
Statement: 
/apps/jenkins/dbase/instantclientORACLE_12_2/sqlplus -v  
--------------------------------------------------------------------------
[Porque_um_artigo_nao_aparece_no_SMPT] $ /apps/jenkins/dbase/instantclientORACLE_12_2/sqlplus -v

SQL*Plus: Release 12.2.0.1.0 Production

Process exited with status 0
--------------------------------------------------------------------------
detected host  = pptlmjenkins01.pt.corp.leroymerlin.com
--------------------------------------------------------------------------
Using ORACLE_HOME =/apps/jenkins/dbase/instantclientORACLE_12_2
--------------------------------------------------------------------------
Running defined script on smpti/********@smpt
Temp script: file:/apps/jenkins/tomcat8.0.47/temp/temp-script-1629468546656679513816661714818.sql
--------------------------------------------------------------------------
[DEBUG] ORACLE_HOME = /apps/jenkins/dbase/instantclientORACLE_12_2
[DEBUG] LD_LIBRARY_PATH  = /apps/jenkins/dbase/instantclientORACLE_12_2/lib:/apps/jenkins/dbase/instantclientORACLE_12_2
java.lang.RuntimeException: TNSNAMES.ORA missing!
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:434)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:195)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1906)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: TNSNAMES.ORA missing!
Finished: FAILURE

But, the tnsnames.ora is there, on TNS_ADMIN... 
/apps/jenkins/dbase/instantclientORACLE_12_2> ls -l *.ora
-rwxr-xr-x. 1 jenkins jenkins 218 Aug 19 17:03 tnsnames.ora

**Comment by boaglio** [comment]
Hi, your **TNS\_ADMIN** is wrong, it should be **/apps/jenkins/dbase/instantclientORACLE\_12\_2**

**Comment by fabiofetter** [comment]
Danm!!!

Ok man, thanks a lot.
