### ISSUE TITLE
custom SQLPATH doesn't appear to work (on Windows at least)

### ISSUE THREAD

**Issue by graemecncs** [jenkinsci/sqlplus-script-runner-plugin#62]
### Version report

Jenkins and plugins versions report:

```
Copy/paste here....
```
Jenkins: 2.263.3
OS: Windows Server 2016 - 10.0
---
bouncycastle-api:2.16.0
command-launcher:1.2
credentials:2.3.14
jdk-tool:1.0
junit:1.29
mapdb-api:1.0.9.0
scm-api:2.6.4
script-security:1.75
sqlplus-script-runner:2.0.15
ssh-credentials:1.17.4
structs:1.20
trilead-api:1.0.4
workflow-api:2.40
workflow-scm-step:2.11
workflow-step-api:2.23

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```
OS: Windows Server 2016 - 10.0
### Reproduction steps

- Step 1... create build using SQL Script Runner
- Step 2...Place sql script (test.sql) in custom SQL path and set custom SQLpath to point to location (d:\Jenkins\sql)
- Step 3 Run build

### Results

Expected result:

script would execute

Actual result:

Jenkins could not find script

Started by user admin
Running as SYSTEM
Building in workspace C:\Users\sysora11test\AppData\Local\Jenkins\.jenkins\workspace\SQL Script test
--------------------------------------------------------------------------
Getting ORACLE_HOME...
--------------------------------------------------------------------------
Using global SQL*Plus location
--------------------------------------------------------------------------
Using global TNS_ADMIN location
TNS_ADMIN: hidden for security reasons
Using custom SQLPATH location
SQLPATH: d:\Jenkins\sql
--------------------------------------------------------------------------
Using global ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =D:\Oracle\FMW
--------------------------------------------------------------------------
Getting SQLPlus version
[SQL Script test] $ D:\Oracle\FMW\BIN\SQLPLUS.EXE -v

SQL*Plus: Release 12.1.0.2.0 Production

Process exited with status 0
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Using ORACLE_HOME =D:\Oracle\FMW
--------------------------------------------------------------------------
Running script C:\Users\sysora11test\AppData\Local\Jenkins\.jenkins\workspace\SQL Script test\TEST.SQL on user1/********@testdb
java.lang.RuntimeException: Unable to read SQL script [C:\Users\sysora11test\AppData\Local\Jenkins\.jenkins\workspace\SQL Script test\TEST.SQL]  !
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:396)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:195)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Unable to read SQL script [C:\Users\sysora11test\AppData\Local\Jenkins\.jenkins\workspace\SQL Script test\TEST.SQL]  !
Finished: FAILURE

**Comment by boaglio** [comment]
Hello, you are not using the latest version, please upgrade and retry.

**Comment by graemecncs** [comment]
Thank you - I updated the plugin and it is now working. I will update the issue.

I appreciate your assistance.


Graeme King

eGrants O&M<https://cnsgov.sharepoint.com/sites/oit/ApplicationManagement/InternalSite/ACCB/Lists/Oracle%2019C%20Environments/Allitemsg.aspx> and Data Warehouse



[cid:9fad696f-c1bc-4303-b85f-2e8f63edfe93]<https://www.americorps.gov/>



250 E Street SW, Washington DC 20525<https://www.google.com/maps/place/250+E+St+SW,+Washington,+DC+20024/data=!4m2!3m1!1s0x89b7b77f66c46ffd:0x5966ac32770cd315?sa=X&ved=2ahUKEwiKkqKY8a3tAhWWFFkFHU0LApsQ8gEwAHoECAcQAQ>

office: (202) 606-7531 cell: (202) 286-1258


________________________________

**Comment by graemecncs** [comment]
Thanks!


Graeme King

eGrants O&M<https://cnsgov.sharepoint.com/sites/oit/ApplicationManagement/InternalSite/ACCB/Lists/Oracle%2019C%20Environments/Allitemsg.aspx> and Data Warehouse



[cid:9dbdad66-5db7-4926-a421-830308174871]<https://www.americorps.gov/>



250 E Street SW, Washington DC 20525<https://www.google.com/maps/place/250+E+St+SW,+Washington,+DC+20024/data=!4m2!3m1!1s0x89b7b77f66c46ffd:0x5966ac32770cd315?sa=X&ved=2ahUKEwiKkqKY8a3tAhWWFFkFHU0LApsQ8gEwAHoECAcQAQ>

office: (202) 606-7531 cell: (202) 286-1258


________________________________
