### ISSUE TITLE
It is not possible to execute a procedure

### ISSUE THREAD

**Issue by alissonrodrigz** [jenkinsci/sqlplus-script-runner-plugin#66]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

1 - Try to execute a script like. I tried in both, "User Defined Script" and "File Script"
set serveroutput ON;
DECLARE 
    i NUMBER; 
BEGIN 
    UPDATE table 
    SET    fields = value
    WHERE  condition; 
    i := SQL%rowcount; 

    IF i = 0 THEN
        insert into table
        Values (Values);
        dbms_output.Put_line('New record inserted!');
    ELSE
        dbms_output.Put_line('Record updated successfully!');
    END IF;
   
    COMMIT; 
    dbms_output.Put_line('Finish');
END;

### Expected Results

Successfully  eexecuted.

### Actual Results

Apparently the script is not recognized.

--------------------------------------------------------------------------
Using ORACLE_HOME =C:\Oracle\instantclient_21_3
--------------------------------------------------------------------------
Running defined script on (...)
Temp script: file:/C:/Windows/TEMP/temp-script-16462433659305296826026458139045.sql
--------------------------------------------------------------------------
[workspace] $ C:\SQLPlus\instantclient_21_3\sqlplus.exe -L ******** @C:\Windows\TEMP\temp-script-16462433659305296826026458139045.sql

SQL*Plus: Release 21.0.0.0.0 - Production on Wed Mar 2 12:49:26 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Last Successful login time: Wed Mar 02 2022 12:48:58 -05:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.14.0.0.0

  8  Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.14.0.0.0
Process exited with status 0
--------------------------------------------------------------------------
Finished: SUCCESS

### Anything else?

It works well if I execute Insert or Update individually.

**Comment by boaglio** [comment]
Before running on Jenkins you should run manually to check if your script is ok.

I think you miss something at the end... you should replace:

```
dbms_output.Put_line('Finish');
END;
```

with:

```
dbms_output.Put_line('Finish');
END;
/
```

**Comment by alissonrodrigz** [comment]
Wow, that was it! Thank you!
