### ISSUE TITLE
[WARNING]Unable to read SQL script [C:\ProgramData\Jenkins\.jenkins\workspace\miworkspace]

### ISSUE THREAD

**Issue by cinemacloudapp** [jenkinsci/sqlplus-script-runner-plugin#68]
Hi I'm running a .sql file on jenkins with oracle sqlplus (SQLPlus Script Runner) and I'm getting these 2 errors:

1.- [WARNING]Unable to read SQL script [C:\ProgramData\Jenkins\.jenkins\workspace\pocPipeline]

2.- SP2-0223: No lines in SQL buffer.

If I execute a direct query it works correctly, code example:

pipeline {
    environment {
        BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
    }
    agent any

    stages {
        stage('build') {
            steps {
                echo "Building..${BRANCH_NAME}"
                updateGitlabCommitStatus name: 'build', state: 'pending'

                script {
                    try {
step([$class: 'SQLPlusRunnerBuilder',credentialsId:'qa1', instance:"${INSTANCE}",scriptType:'userDefined', script: '',scriptContent: 'select * from mapping;'])

echo "Connected to oracle on instance ${INSTANCE}"
                        updateGitlabCommitStatus name: 'build', state: 'success'
                    } catch(Exception e) {
                        echo 'Exception occurred: ' + e.toString()
                        updateGitlabCommitStatus name: 'build', state: 'failed'
                        sh 'exit 1'
                    }
                }
            }
        }
    }
}

If I execute a file, it fails:

code inside update.sql file (
DROP TABLE MAPPING;
/

CREATE TABLE MAPPING
(
   ID NUMBER NOT NULL,
   FECHA_CREACION DATE DEFAULT SYSDATE,
   USER_CREATION VARCHAR2 (30) DEFAULT USER,
   XML BLOBs
);
/
)

pipeline {
    environment {
        BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
    }
    agent any

    stages {
        stage('build') {
            steps {
                echo "Building..${BRANCH_NAME}"
                updateGitlabCommitStatus name: 'build', state: 'pending'

                script {
                    try {
step([$class: 'SQLPlusRunnerBuilder',credentialsId:'qa1', instance:"${INSTANCE}",scriptType:'userDefined', script: 'update.sql',scriptContent: ''])

echo "Connected to oracle on instance ${INSTANCE}"
                        updateGitlabCommitStatus name: 'build', state: 'success'
                    } catch(Exception e) {
                        echo 'Exception occurred: ' + e.toString()
                        updateGitlabCommitStatus name: 'build', state: 'failed'
                        sh 'exit 1'
                    }
                }
            }
        }
    }
}

**Comment by boaglio** [comment]
Your _scriptType_ is wrong, it should be "file".
Inside your script file you should remove all blank lines and semicolons.

**Comment by cinemacloudapp** [comment]
solvex, thank

> Your _scriptType_ is wrong, it should be "file". Inside your script file you should remove all blank lines and semicolons.

solvex, thank.
