### ISSUE TITLE
isSysdba option for pipelines is not documented

### ISSUE THREAD

**Issue by cmolinah** [jenkinsci/sqlplus-script-runner-plugin#72]
When using sqlplus-script-runner in a pipeline we can use `isSysdba:'true'`. However, this is not documented in https://plugins.jenkins.io/sqlplus-script-runner/

I was lucky to find the option checking the source code because it was one of the last commits done.

Thanks for maintaining this great plugin.

**Comment by boaglio** [comment]
Hi, I am having issues to update my plugin, but in the next update the doc will be updated, thanks.
