### ISSUE TITLE
File Script looking for sql file in default workspace

### ISSUE THREAD

**Issue by birajasahoo7** [jenkinsci/sqlplus-script-runner-plugin#73]
Hello, 
I am new to SQLScriptRunner. 
I am trying to run a filescript using sqlscript runner. But when I give the name of the script in "File Script" and provide the path in "Custom SQLPath" and try to build the job it is failing. It is trying to search in the default workspace.
FileScript: Query1.sql
Custom SQLPath: C:\Biraja\Jenkins\Scripts

Error:
Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

SP2-0310: unable to open file "C:\Biraja\Jenkins\JenkinsHome\workspace\SQLScriptRunner\Query1.sql"

Even if I set the "File Script" to full path of the script, it is still trying to search for the file in the workspace.
FileScript: C:\Biraja\Jenkins\Scripts\Query1.sql

Error:
Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production

SP2-0310: unable to open file "C:\Biraja\Jenkins\JenkinsHome\workspace\SQLScriptRunner\C:\Biraja\Jenkins\Scripts\Query1.sql"

Please guide me what  how can I make the file read from the correct place instead in the default workspace.
Thank You.

**Comment by boaglio** [comment]
Please provide:


-     Jenkins server Operation System;
-     Jenkins version ;
-     Where SQLPlus Script Runner is running (local machine or slave machine);
-     Slave machine Operation System (if applicable);
-     Oracle Database version;
-     Oracle SQL*Plus version;
-     Build log with **debug** info enabled.
-

**Comment by birajasahoo7** [comment]
Thank You for the reply.

Jenkins server Operation System : Windows 11
Jenkins version : 2.414.2
Where SQLPlus Script Runner is running (local machine or slave machine); Local machine
Slave machine Operation System (if applicable);
Oracle Database version : 18.9.1.0.0
Oracle SQL*Plus version : 12.2.0.1.0
Build log with debug info enabled.
[Console_log.txt](https://github.com/jenkinsci/sqlplus-script-runner-plugin/files/12803419/Console_log.txt)

I have attached the console log. If there is a debug mode for the Build, please let me know how can I enable it during the build. I tried searching how to enable the debug mode, but wasn't successful in doing so.

But as I mentioned in my previous comment, SQLScriptRunner is looking for the sql script in default workspace location as below:

Started by user admin
Running as SYSTEM
Building in workspace C:\Biraja\Jenkins\JenkinsHome\workspace\SQLScriptRunner
...
...
Using ORACLE_HOME =C:\Oracle\Ora12_2_0_1_x64
Running script C:\Biraja\Jenkins\JenkinsHome\workspace\SQLScriptRunner\C:\Biraja\Jenkins\Scripts\Query1.sql on testuser/********@oradb1
[WARNING]Unable to read SQL script [C:\Biraja\Jenkins\JenkinsHome\workspace\SQLScriptRunner\C:\Biraja\Jenkins\Scripts\Query1.sql] !

Thank You again for all the help.

**Comment by boaglio** [comment]
what is the **sqlplus-script-runner-plugin** version you are using ?

**Comment by birajasahoo7** [comment]
SQLPlus Script Runner
Version2.0.25

**Comment by boaglio** [comment]
It was a bug and was fixed, please try version 3.0.0 , it is already deployed, it will be available soon.
