### ISSUE TITLE
ORACLE_HOME doesn't exist

### ISSUE THREAD

**Issue by Anas-beshara** [jenkinsci/sqlplus-script-runner-plugin#74]
Although I specified the right path for oracle home in the general configuration for jenkins by it still says:
java.lang.RuntimeException: ORACLE_HOME directory [/usr/lib/oracle/21/client64] does not exist!

I followed these link but the issue still existing:
https://github.com/jenkinsci/sqlplus-script-runner-plugin/issues/18

### Expected Results

Connect and run the specified sql query

### Actual Results

Using global ORACLE_HOME
java.lang.RuntimeException: ORACLE_HOME directory [/usr/lib/oracle/21/client64] does not exist!

**Comment by boaglio** [comment]
This plugin is just a SQL*Plus wrapper, if it is not working, your env has problems.
You should try to run sqlplus with the same Jenkins user (jenkins or root). 
Maybe Jenkins user can't access ORACLE_HOME.

**Comment by Anas-beshara** [comment]
Thanks @boaglio 

I already did that and it is working fine when I tried to run sqlplus command on my machine itself using root user which is also used by jenkins pipeline but I faced this when I tried to do the same with the plugin.
So I think my env should be fine.

**Comment by boaglio** [comment]
This plugin has thousands of active users, if you still believe it is a bug, I need way more info, debug mode active,  details from your Jenkins version, plugin version,  your job config, a full log of a build with this error, etc.

**Comment by Anas-beshara** [comment]
@boaglio 
Sure and thanks in advance!

- Jenkins version: 2.389
- Plugin version: 2.025
- I attached the screenshots for configuration and build output:
![global](https://github.com/jenkinsci/sqlplus-script-runner-plugin/assets/127212663/f5372358-6e87-49bd-96a1-0ea949b77606)
![pipe](https://github.com/jenkinsci/sqlplus-script-runner-plugin/assets/127212663/1745ff43-6951-4586-aab3-15a12ed81e9a)
![build](https://github.com/jenkinsci/sqlplus-script-runner-plugin/assets/127212663/2b10312a-cf68-4e5c-955d-4101def88ec9)

**Comment by boaglio** [comment]
please use the latest version (3.0.0)

**Comment by Anas-beshara** [comment]
@boaglio 
This is the one I can find when I search in plugin manager:
![ver](https://github.com/jenkinsci/sqlplus-script-runner-plugin/assets/127212663/ba0332e1-ed32-43e4-9f4c-a98be9cbc341)

Should I uninstall then reinstall ?

**Comment by boaglio** [comment]
Yes, and you need to use Java 11+.

**Comment by Anas-beshara** [comment]
@boaglio 
I uninstalled the plugin but when I tried to install again it still show 2.0.25 version in the plugin manager, how can I get the latest version 3.0.0 ?

**Comment by boaglio** [comment]
You are using an old Jenkins version, you should upgrade to at least 2.414.2+ (which is base from 3.0.0), like  latest LTS version: 2.426.2.

**Comment by Anas-beshara** [comment]
@boaglio 
Ok, I will try
many thanks

**Comment by Anas-beshara** [comment]
@boaglio 
Hello again
Now I have:
-jenkins version: 2.437
-plugin version: 3.0.0
-Java11
but unfortunately still have the same error:
"Using global ORACLE_HOME
java.lang.RuntimeException: ORACLE_HOME directory [/usr/lib/oracle/21/client64] does not exist!"

**Comment by Anas-beshara** [comment]
@boaglio 
Hello again
Now I have:
jenkins version: 2.437
plugin version: 3.0.0
Java11
but unfortunately still have the same error:
"Using global ORACLE_HOME
java.lang.RuntimeException: ORACLE_HOME directory [/usr/lib/oracle/21/client64] does not exist!"

**Comment by boaglio** [comment]
How are you running Jenkins ? 
Docker? installed package? installed war ?

**Comment by Anas-beshara** [comment]
Docker Compose

**Comment by boaglio** [comment]
please share your docker-compose.yaml

**Comment by Anas-beshara** [comment]
version: '3'
services:
  jenkins:
    restart: always
    #build: .
    image: jenkins/jenkins:latest-jdk11
    ports:
      - "50000:50000"
      - "80:8080"
    volumes:
      - ./jenkins-log:/var/log/jenkins
      - ./jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:

**Comment by boaglio** [comment]
If you want to use Jenkins + SQL Plus, you docker image needs to have both, but you are using only Jenkins. 

That's why you get "/usr/lib/oracle/21/client64 does not exist", it doesn't exist in your docker instance, just in your local machine. 

``` 
# docker compose start
[+] Running 1/1
 ✔ Container j-jenkins-1  Started                                                                                                                                                                                           0.7s 
# docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS         PORTS                                                                                      NAMES
f1f77bbf5ed6   jenkins/jenkins:latest-jdk11   "/usr/bin/tini -- /u…"   45 seconds ago   Up 5 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:50000->50000/tcp, :::50000->50000/tcp   j-jenkins-1

# docker exec -it f1f77bbf5ed6 bash
jenkins@f1f77bbf5ed6:/$ ls /usr/lib/oracle/21/client64 
ls: cannot access '/usr/lib/oracle/21/client64': No such file or directory
jenkins@f1f77bbf5ed6:/$ 
```

The easier way is install Jenkins in your machine as a service , running with docker is way more complex because you will need to include everything in the running instance. 

Since is not a bug, issue closed.

**Comment by Anas-beshara** [comment]
@boaglio 
Many thanks for your clarification
