### ISSUE TITLE
Global TNS_ADMIN is not set

### ISSUE THREAD

**Issue by njimenezotto** [jenkinsci/sqlplus-script-runner-plugin#76]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux Alpine in agents

### Reproduction steps

1. Set Global TNS_ADMIN in configuration
2. Run a job

### Expected Results

TNS_ADMIN is set

### Actual Results

TNS_ADMIN is equal to ORACLE_HOME

### Are you interested in contributing a fix?

PR is already created
https://github.com/jenkinsci/sqlplus-script-runner-plugin/pull/75

**Comment by boaglio** [comment]
Fixed on version 3.0.1, thanks!
