### ISSUE TITLE
enable/disable debug in a pipeline

### ISSUE THREAD

**Issue by martens-d** [jenkinsci/sqlplus-script-runner-plugin#78]
### What feature do you want to see added?

is it possible to make debug selectable not globally but when I start it?

```
something like:
step([$class: 'SQLPlusRunnerBuilder',
        debug: true,                                              // <-- like so
        credentialsId: CREDENTIALS,
        ...)
```

Now that I think about it, Version display as well.

I don't want debug infos in pipelines in production, but I like to have additional infos when programming.

**Comment by boaglio** [comment]
Hi, I don't think this is necessary, but if you really want it you can send a Pull Request .
