### ISSUE TITLE
libsqlplus.so error

### ISSUE THREAD

**Issue by tiffanyfb** [jenkinsci/sqlplus-script-runner-plugin#8]
When attempting to use the SQLPlus Script Runner, it's failing with "error while loading shared libraries: libsqlplus.so: cannot open shared object file: No such file or directory" errors.  The LD_LIBRARY_PATH parameter needs to be set.  I've tried various way to set the parameter in Jenkins, but the plug-in still isn't working.  How can I avoid this error?

**Comment by boaglio** [comment]
LD_LIBRARY_PATH it should be $ORACLE_HOME\lib , where have files like libsqlplus.so .

You should provide your environment like standard Oracle installation:

 $ORACLE_HOME\bin\ - sqlplus binary
 $ORACLE_HOME\lib - sqlplus libraries
 $ORACLE_HOME\network\admin - tnsnames file

**Comment by tiffanyfb** [comment]
Where/How do I set those variables?  Files exist in those places, but the plug-in doesn't recognize them.  I can run SQL*Plus from command line on the Jenkins servers with no problems (after setting LD_LIBRARY_PATH).

**Comment by qkniazi** [comment]
Hy can you help me please
to setup via team viewer ?

Sent from my iPhone

On Jun 26, 2017, at 1:03 PM, tiffanyfb <notifications@github.com<mailto:notifications@github.com>> wrote:


Where/How do I set those variables? Files exist in those places, but the plug-in doesn't recognize them. I can run SQL*Plus from command line on the Jenkins servers with no problems (after setting LD_LIBRARY_PATH).

**Comment by boaglio** [comment]
I think there is something about Oracle Instant Client... send me a private message, I will try to create a modified version for you

**Comment by tiffanyfb** [comment]
Thanks for your help on this.  I'm unable to see a way to PM you.  I installed the 12.1.0.2.0 client and SQLPlus libraries located here:  http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html .
instantclient-basic-linux.x64-12.1.0.2.0.zip
instantclient-sqlplus-linux.x64-12.1.0.2.0.zip

**Comment by boaglio** [comment]
Today I released a new version that supports Instant Client and tries to locate sqlplus exec file and tnsnames.ora before set the environment variables.

**Comment by qkniazi** [comment]
Sir how can we execute  git hub or bitbucket repertory by using your plugin ?

Sent from my iPhone

On Jul 9, 2017, at 11:29 AM, Fernando Boaglio <notifications@github.com<mailto:notifications@github.com>> wrote:


Today I released a new version that supports Instant Client and tries to locate sqlplus exec file and tnsnames.ora before set the environment variables.

**Comment by boaglio** [comment]
Before build you have to checkout your code from Github/Bitbucket... that's it.

**Comment by qkniazi** [comment]
Ok i will try and let you know. Thanks

Sent from my iPhone

On Jul 9, 2017, at 2:02 PM, Fernando Boaglio <notifications@github.com<mailto:notifications@github.com>> wrote:


Before build you have to checkout your code from Github/Bitbucket... that's it.

**Comment by qkniazi** [comment]
sir you send me screen snapshots that how you connected it to bitbucket or GitHub please. ? also if you used environment variables.

thanks you


Qamar Khan



________________________________

**Comment by boaglio** [comment]
Google is your friend https://www.blazemeter.com/blog/how-start-working-github-plugin-jenkins

**Comment by tiffanyfb** [comment]
Thanks much for the update.  It's working for me now.  I did get an error due to it adding a double slash to a path, but the sql statement succeeded.

```
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/workspace/DBA_Test2
--------------------------------------------------------------------------
Getting ORACLE_HOME...
--------------------------------------------------------------------------
Using custom ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =/opt/app/oracle/product/12.1.0.2/client
--------------------------------------------------------------------------
Getting SQLPlus version
SQL*Plus exec file = sqlplus
found SQL*Plus on /opt/app/oracle/product/12.1.0.2/client
Process exited with status 127
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Using ORACLE_HOME =/opt/app/oracle/product/12.1.0.2/client
--------------------------------------------------------------------------
/opt/app/oracle/product/12.1.0.2/client//sqlplus: error while loading shared libraries: libsqlplus.so: cannot open shared object file: No such file or directory
Running defined script on bw/********@ORDERDEV
Temp script: /tmp/temp-script-14997147215729179282932362721703.sql
--------------------------------------------------------------------------
Work Directory = /var/lib/jenkins/workspace/DBA_Test2
SQL*Plus exec file = sqlplus
Process exited with status 0
--------------------------------------------------------------------------

SQL*Plus: Release 12.1.0.2.0 Production on Mon Jul 10 12:25:22 2017

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Mon Jul 10 2017 12:16:36 PST8PDT PDT

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Advanced Analytics and Real Application Testing options


SYSDATE
---------
10-JUL-17

Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Advanced Analytics and Real Application Testing options
Finished: SUCCESS
```

**Comment by boaglio** [comment]
Great @tiffanyfb  =)

**Comment by qkniazi** [comment]
At this point I am able to run the script from my local computer and from bit-bucket. I have a quick question,, In your tool there is option to enter filename.sql .,,,  what about if my repository contain 100 files. does it means I have to setup for each file separately,?

THX

Qamar Khan

________________________________

**Comment by boaglio** [comment]
Hi, you can't do that because it is a SQL*Plus limitation. You can solve it in Oracle way, creating one script to call all the others.

**Comment by srneer** [comment]
Hi tiffanyfb, can you please tell about the update. I am also facing exactly same issue.
