### ISSUE TITLE
SQLPLUS Script Runner error

### ISSUE THREAD

**Issue by qkniazi** [jenkinsci/sqlplus-script-runner-plugin#9]
![jenkinserror](https://user-images.githubusercontent.com/19601229/27927500-97d2aa58-6251-11e7-9eda-640a28b2e64c.JPG)
![database](https://user-images.githubusercontent.com/19601229/27927509-9d743986-6251-11e7-939f-388f8bfcf594.JPG)
I am able to connect and run the query outside Jenkins. but when I run through Jenkins , it never runs. above is the script runner console output.

**Comment by qkniazi** [comment]
@boaglio 
working for me:: what I did, is I installed oracle client as admin option. used the default folder locations for oracle client. set up the TNS file and ORACLE_HOME ,,, and it started working

**Comment by boaglio** [comment]
Today I released a new version that supports Instant Client and tries to locate _sqlplus_ exec file and _tnsnames.ora_ before set the environment variables.
